#!/usr/bin/env bash
# security of server matter

sudo apt-get update
sudo apt-get install ufw -y
sudo ufw status verbose
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
